version: '5.5.1'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce'
    container_name: my-gitlab-server
    ports:
      - '8001:80'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'P@v@n@252004'
        puma['worker_processes'] = 0